#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.6f1_c591d9a97a0b"
#define UNITY_VERSION_FULL_NICE "2018.2.6f1 (c591d9a97a0b)"
#define UNITY_VERSION_BLD 12947929
#define UNITY_VERSION_DATE 1535016090
#define UNITY_VERSION_WIN "2018.2.6.12947929"
#define UNITY_VERSION_BRANCH "2018.2/release"
